algorandfoundation/reti

ui/.gitignore, ui/netlify.toml, ui/vercel.json
Since the example UI is a single page application with client side routing, manually typing a URL other than the root `/` index route results in a 404 error. Same with refreshing the page.
This adds configuration settings for Vercel and Netlify that rewrites HTTP requests on the server to index.html, where the router lives, so it can load and display the requested route.
=> fix(ui): prevent 404 - NotFound errors on refresh

ui/src/api/queries.ts, ui/src/components/ValidatorTable.tsx, ui/src/utils/contracts.ts
Enhanced the max stake per-pool calculation function to use the 'protocol constraints' and taking lesser of (max per validator / num pools) or protocol max per pool.  The constraints will also be updated at least once every 30 minutes.
=> fix(ui): Update 'max stake' allowed per validator calculation

.github/workflows/ci-ui.yaml
The UI's CI workflow will only run when there are changes to files in the `ui` folder. An additional check prevents the workflow from running a second time for `chore: release vX.X.X` commits to the `dev` branch.
=> ci(ui): add conditions for running CI workflow for UI

ui/src/components/AddValidatorForm.tsx
The nfdForInfo must be an NFD owned by the activeAddress.
This also updates the form to support multiple validation errors.
=> fix(ui): verify activeAddress owns the specified nfdForInfo

ui/src/api/contracts.ts, ui/src/components/NfdAvatar.tsx, ui/src/components/NfdThumbnail.tsx, ui/src/components/ValidatorTable.tsx, ui/src/interfaces/validator.ts
This makes a few changes to improve the way NFDs are displayed in the validator table:
- the Validator column has a max width set and the `NfdThumbnail` can be truncated for long names
- a boolean `tooltip` prop will show potentially-truncated NFD names in full in a tooltip on hover
- NFD data is fetched up front along with validator data so it's not being fetched asynchronously in the table cell
- `NfdThumbnail` can either accept a `nameOrId` prop (to fetch) or an NFD object if the data is already available
- `NfdThumbnail` is conditionally memoized if the data is passed in as a prop to limit unnecessary re-renders
- `NfdAvatar` is memoized
=> feat(ui): improved nfdForInfo display in ValidatorTable

ui/src/components/ValidatorTable.tsx
Stopping event propagation prevents click handlers from triggering navigation to the validator details page. The menu trigger already did this but the menu items did not.
This change stops the event propagation for the menu items as well.
=> fix(ui): stop propagation clicking ValidatorTable menu items

ui/src/components/AddPoolModal.tsx, ui/src/components/AddStakeModal.tsx, ui/src/components/UnstakeModal.tsx
Previously optimistic updates were used to update the cache after a pool or stake mutation. This is cumbersome and prone to errors, since the logic to immutably update deeply-nested data in multiple queries can be complex.
Instead, we now invalidate the cache for queries that return validator, pool, or stake data that was mutated. This is done by calling `invalidateQueries` with a predicate that matches the keys of the affected queries, then calling `router.invalidate()` to trigger refetches.
To avoid refetching all (mostly unaffected) validators, the `['validators']` query is still optimistically updated as before.
=> fix(ui): invalidate cached queries on pool/stake mutation

nodemgr/daemon.go, nodemgr/internal/lib/reti/reti.go, nodemgr/internal/lib/reti/validator.go, nodemgr/svc.go, nodemgr/validatorcmds.go
Exit the daemon on manager address change so that on restart the new manager address is used and keys verified.
Otherwise, mnemonics for new manager might not be available for subsequent transactions.
=> fix(nodemgr): Monitor the manager address changing and gracefully exit

ui/src/api/contracts.ts, ui/src/components/AddStakeModal.tsx, ui/src/components/AddValidatorForm.tsx, ui/src/components/StakingTable.tsx, ui/src/components/UnstakeModal.tsx, ui/src/lib/makeEmptyTransactionSigner.ts, ui/src/main.tsx, ui/src/providers/AuthAddressProvider.tsx, ui/src/utils/development.ts
Using the algosdk v2.7.0 `makeEmptyTransactionSigner` function for simulate calls with the "allow empty signatures" option currently fails if the sender is a rekeyed account.
This solution is based on the workaround @joe-p offered in a discussion about the issue: https://github.com/algorand/go-algorand/issues/5914#issuecomment-1904781807
A React Context provider contains an effect that runs whenever use-wallet's `activeAddress` changes, looking on-chain to see if the account has been rekeyed. If so, its authorized address (spending key) is stored and exposed by the `useAuthAddress` hook where it can be accessed anywhere in the app.
Any function that makes a contract call using simulate from the active account now also accepts an additional `authAddr` argument, which is then passed to the …
=> feat(ui): support simulate calls from rekeyed accounts

ui/src/components/ValidatorDetails/PoolsChart.tsx, ui/src/components/ValidatorDetails/StakingDetails.tsx
The only way to highlight a pool in the donut chart is to click it. This simulates that behavior when selecting a pool from the dropdown menu in StakingDetails.
When selecting a pool from the menu, the donut chart will highlight the corresponding pool. It will reset if "All Pools" is selected.
If a staking pool has no stake, it must still appear in the chart for this to work. The solution here is a bit of a hack: in the chart, pools with no stake are set to 1 microalgo. It is displayed as a barely perceptible sliver in the chart, but it is enough to allow the chart to highlight the pool when selected from the dropdown. Its tooltip shows the correct amount of 0 stake.
=> feat(ui): simulate donut chart clicks on dropdown change

ui/src/api/contracts.ts, ui/src/components/AddStakeModal.tsx, ui/src/components/StakingTable.tsx, ui/src/components/UnstakeModal.tsx, ui/src/components/ValidatorDetails/StakingDetails.tsx, ui/src/components/ValidatorTable.tsx, ui/src/components/ui/alert.tsx, ui/src/interfaces/validator.ts, ui/src/utils/contracts.ts
- Shows available balance to stake
- Shows target pool depending on the stake amount entered
- Fixes minimum stake validation (only enforce minimum entry stake if first time staking to validator)
- Fixes maximum available to stake calculation, using protocol constraints if `maxAlgoPerPool` is not set in validator config
- Clears any errors when the modal is closed
- Nicer "first time stakers fee" message, shown in an alert/callout
=> feat(ui): AddStakeModal improvements

.github/workflows/ci-ui.yaml, ui/.env.test, ui/.gitignore, ui/package.json, ui/src/api/contracts.ts, ui/src/components/StakingTable.tsx, ui/src/utils/contracts.spec.ts, ui/src/utils/contracts.ts
This refactors the logic to calculate a staker's reward eligibility for display in the dashboard staking table.
The `dayjs` library makes time measurements and calculations more declarative and readable, so issues are easier to debug.
Moving the code to a utility function simplifies the staking column definition in the table and makes the logic testable (unit tests are added).
=> refactor(ui): use dayjs to calculate reward eligibility

ui/src/components/ValidatorTable.tsx, ui/src/hooks/useLocalStorage.ts, ui/src/utils/dayjs.ts
This makes two improvements to the `ValidatorTable`:
- allow more space for validator name, especially on larger screens
- rename "Payout Frequency" to "Epoch" and display values in compact format
- remove "# " from "# Pools"
- wrapper for `useState` that reads/writes to local storage to persist state
- supports optional versioning and migration, based on Zustand's `persist` middleware: https://github.com/pmndrs/zustand/blob/main/docs/integrations/persisting-store-data.md
- used to persist `ValidatorTable` column sorting/filtering
=> fix(ui): improvements to ValidatorTable UX/display

ui/src/components/ValidatorDetails/StakingDetails.tsx, ui/src/hooks/useStakersChartData.ts
Whenn switching between pools in StakingDetails, the aggregation logic for "all pools" that calculates each stakers' total balance was not correctly isolated. If a staker was in multiple pools the total balance was compounding each time and would get bigger and bigger each time the selected pool changed. This fix properly resets the aggregation logic.
It also refactors the logic into a custom hook, `useStakersChartData`, which simplifies the component and isolates the logic so it can be tested.
=> fix(ui): recomputation of stakers chart data

pnpm-lock.yaml, ui/package.json, ui/vite.config.ts
The testing setup added in https://github.com/TxnLab/reti/pull/103 includes a function that uses `Buffer.from` to set an encoded note on simulate calls. This works in a test environment but fails in the browser without a polyfill for the `Buffer` API.
This adds `vite-plugin-node-polyfills` as recommended in https://github.com/vitejs/vite/discussions/2785#discussioncomment-7803485
=> fix(ui): install polyfill for Buffer

renovate.json
What we want for our Renovate configuration is pretty specific, so we can't rely on presets to get the job done. After some research I realized my mental model was wrong and there is a better approach to get the fine-grained control we want.
The crucial difference here in the `npm` config is the `additionalBranchPrefix` setting, which will prepend branches with the name of the package.json's parent folder. This effectively separates all PRs by project: `contracts`, `bootstrap`, and `ui`.
I've set some updates to automerge. Anything related to ESLint/Prettier has 100% coverage in CI (checks will fail if anything breaks), so there's really no reason to manually review and merge. But I'm not sure if this will work since we have a CODEOWNERS file that may require approval before merging. …
=> chore(renovate): better grouping and overall config

ui/src/utils/contracts.ts
When adding stake to a validator's first pool, bypass the `maxAvailableToStake` reduce function and return `maxAlgoPerPool` from constraints.
=> fix(ui): account for no pools in calculateMaxAvailableToStake

ui/src/api/queries.ts, ui/src/components/AddPoolModal.tsx, ui/src/components/AddStakeModal.tsx, ui/src/components/UnstakeModal.tsx, ui/src/routes/index.tsx, ui/src/routes/validators_.$validatorId.tsx, ui/src/utils/contracts.ts
Manual updates to the `'validators'` query cache are complex, prone to error, and brittle. Refetching the validator after a mutation (e.g., adding a new pool or staking/unstaking) and updating just that validator in the collection with real data is a better solution in every way. The only cost is a single extra network request.
This fixes a bug where `validator.pools` was not being updated after adding a pool or staking/unstaking.
=> fix(ui): refetch new validator data instead of manually updating

ui/src/api/nfd.ts, ui/src/api/queries.ts, ui/src/components/AddStakeModal.tsx, ui/src/components/ValidatorDetails/EditCommissionAccount.tsx, ui/src/components/ValidatorDetails/EditEntryGating.tsx, ui/src/components/ValidatorDetails/EditManagerAccount.tsx, ui/src/components/ValidatorDetails/EditNfdForInfo.tsx, ui/src/components/ValidatorDetails/EditRewardPerPayout.tsx, ui/src/components/ValidatorDetails/EditSunsettingInfo.tsx, ui/src/components/ui/dialog.tsx, ui/src/utils/contracts.ts
There was an issue with the way segment gating assets were being checked, and the `AddStakeModal` was showing the add stake form even if the staker did not hold a valid segment.
This refactors the logic for whether to show the "Gating Asset Required" message in the modal, and also for determining the `valueToVerify` that is passed with the `addStake` contract call.
While this does fix things from the UI side, when attempting to add stake while holding a valid segment, the `addStake` call is still rejected despite passing the held segment's app ID as the `valueToVerify`. The error seems to correspond to this assertion in the contract: https://github.com/TxnLab/reti/blob/dev/contracts/contracts/validatorRegistry.algo.ts#L1350
=> fix(ui): all gating types correctly check for valid gating asset

ui/src/utils/contracts.spec.ts, ui/src/utils/contracts.ts
Instead of measuring the time remaining in the epoch to determine rewards eligibility, the time before entering the epoch was being used.
This fixes the bug and updates its tests.
=> fix(ui): fix calculation of rewards eligibility

ui/src/components/AddStakeModal.tsx, ui/src/components/UnstakeModal.tsx
When adding or removing stake from the `StakingDetails` component (on the validator details page), the progress bar showing current stake in proportion to max stake does not update. Its query is not among the ones being invalidated on success.
This invalidates the query after a mutation that changes the total amount staked in a pool.
=> fix(ui): invalidate 'pools-info' query after adding or removing stake

ui/src/api/contracts.ts, ui/src/interfaces/validator.ts, ui/src/utils/contracts.ts, ui/src/utils/tests/fixtures/validators.ts
This removes fetches for token payout ratios for each validator, as they are only needed internally and for testing. 
This will save lots of unnecessary simulate calls as this was being fetched (and refetched) for every validator in the dashboard.
=> fix(ui): token payout ratios are not needed/used in the UI

ui/src/api/algod.ts, ui/src/api/contracts.ts, ui/src/components/AddValidatorForm.tsx, ui/src/components/AssetLookup.tsx, ui/src/components/ValidatorDetails/Details.tsx, ui/src/interfaces/validator.ts, ui/src/utils/format.spec.ts, ui/src/utils/format.ts, ui/src/utils/validation.ts
This makes a number of improvements to how the UI handles reward tokens:
- fetch asset info from reward token ID (debounced), showing unit name and green check mark if it exists
- validate reward token is an actual asset, prevents form submission if not
- validate reward per payout is set if reward token is set
- reward per payout is expected in whole units, not base units
- fetches reward token's asset info and sets it to the `Validator`'s `rewardToken?: Asset` property
- show reward token name/unit-name in validator details instead of ID
- reward token is a link to the asset in block explorer
- show reward per payout in whole units of asset with unit name
Fixes a bug in `formatNumber` where no decimals were shown if `options.precision` was undefined. Now if precision is unset all …
=> feat(ui): reward token improvements

ui/src/components/AddPoolModal.tsx, ui/src/components/AddStakeModal.tsx, ui/src/components/UnstakeModal.tsx, ui/src/components/ValidatorDetails/Details.tsx, ui/src/components/ValidatorTable.tsx, ui/src/hooks/useBlockTime.ts, ui/src/utils/development.ts, ui/src/utils/format.spec.ts, ui/src/utils/format.ts
This consolidates all of the various number formatting functions so they are all based on `formatAmount`, and accepts its `options` object.
The `formatAmount` function itself (renamed from `formatNumber`) is refactored to use Big.js and accept numbers, bigints, or strings for the `amount`.
=> feat(ui): format/convert number util function improvements

ui/src/components/StakingTable.tsx, ui/src/components/ValidatorTable.tsx, ui/src/utils/development.tsx
This updates the `simulateEpoch` function to work with the new rounds-based epoch lengths.
First a hard coded amount (currently 100 ALGO) is sent to each of the validator's pools.
The only way to advance blocks on localnet is to sign and send zero-pay transactions to a test account. Using 320-round postdating and the validator's epoch length, the number of blocks required is calculated and a loop signs and sends a transaction for each block until an epoch has transpired.
Then the `epochBalanceUpdate` call is fired for each pool. This triggers payouts of the rewards based on stake and eligibility. Since these calls require signatures, after each call the success toast displays a button to click to advance to the next pool (to prevent errors in wallets like Lute which require user …
=> feat(ui): update simulateEpoch to support rounds

ui/src/utils/development.tsx
The KMD client is only exposed in localnet environment, but it was being instantiated at the top level of /src/utils/devlopment.tsx
This broke the app in staging/prod (i.e., testnet).
Now it is instantiated inside the `incrementRoundNumberBy` function, so only when used by the development-only `simulateEpoch` function.
=> fix(ui): instantiate KMD client inside dev-only function

ui/src/api/contracts.ts
When calling `fetchStakedInfoForPool` for a staking pool with no stakers (yet), attempting to fetch that pool contract's 'stakers' box value will return a 404 error. An error message is shown by `StakingDetails`.
Now we catch the error from `getBoxValue('stakers')` and if it's a 404, return an empty `StakedInfo` array.
=> fix(ui): catch and handle 'stakers' box value 404 errors

contracts/bootstrap/package.json, contracts/package.json, pnpm-lock.yaml
This upgrades `@algorandfoundation/algokit-utils` to v6.0.4 in contracts and bootstrap.
It also pins the versions of this and `algosdk`, to prevent inadvertent upgrades when running `pnpm install`. We always want to be on the exact version we expect.
=> chore: upgrade algokit-utils and pin algosdk

ui/src/api/contracts.ts, ui/src/components/AddPoolModal.tsx
In the add pool workflow, the 'pools-info' query was being invalidated after step 1 when the pool is still in the "limbo" state before the storage MBR is paid. That's why `fetchStakedInfoForPool` was throwing a 404 error: the 'stakers' box value has not been set yet.
This moves invalidation to step 2, after the box value has been set. No more error.
This PR also reverts the change in https://github.com/TxnLab/reti/pull/165
=> fix(ui): invalidate 'pools-info' query after box value is set

ui/src/components/AddValidatorForm.tsx, ui/src/components/ValidatorDetails/EditRewardPerPayout.tsx
This was updated in `AddValidatorForm` but not in the modal for editing reward token payout amount.
The amount entered should be in whole units (validation already supports this), and when the form is submitted the amount is converted to base units and passed to the `changeValidatorRewardInfo` method call.
=> fix(ui): edit token payout converts amount to base units

ui/src/components/AddValidatorForm.tsx, ui/src/components/ValidatorDetails/EditRewardPerPayout.tsx
When the `EditRewardPerPayout` modal opens, the input is pre-populated with the current value for `rewardPerPayout`, which can then be edited.
The form expects this value to be in whole units, but the initial value was the raw base unit value from the validator config.
This correctly converts the initial value to its whole unit amount. If that value is edited, it is converted back to base units before it is submitted.
In both the `EditRewardPerPayout` modal and the `AddValidatorForm`, a description now instructs the user to enter whole unit amounts. They should only ever think of reward token amounts in terms of whole units.
This also updates the `EditRewardPerPayout` modal description to show the unit name of the reward token, e.g., "Set the amount of PEPE paid out each epoch for …
=> fix(ui): convert current rewardPerPayout to whole units

ui/src/api/contracts.ts
In `addValidator`, we fetch the suggested params from the params cache then need to set `flatFee` and `fee` before using them to pay the validator MBR.
By mutating the object's properties directly, the values set are then being used everywhere we fetch cached params in subsequent transactions (until fresh data is refetched).
This updates that step to change the properties immutably, by creating a new object, spreading the cached params into it, and updating that object's properties.
=> fix(ui): don't mutate cached params in addValidator

ui/src/components/AddValidatorForm.tsx
An error was added to handle `rewardToken` being null when converting `values.rewardPerPayout` to base units. It now uses optional chaining with a fallback instead.
=> fix(ui): fix AddValidatorForm onSubmit regression (error if no token set)

ui/src/components/AddStakeModal.tsx, ui/src/components/UnstakeModal.tsx
Pressing Enter in `AddStakeModal` or `UnstakeModal` calls the function to set the maximum amount instead of submitting the form.
This adds `type="button"` to the MAX button to prevent it from catching the keypress event.
=> fix(ui): pressing Enter should submit add/remove stake form

ui/src/api/contracts.ts
This increases opcode budget, fixing failed `addStake` app calls for validators with NFD segment entry gating.
=> fix(ui): add 2nd gas call to addStake

ui/src/api/contracts.ts, ui/src/components/AddPoolModal.tsx, ui/src/components/AddValidatorForm.tsx, ui/src/components/AssetLookup.tsx, ui/src/components/DisplayAsset.tsx, ui/src/components/StakingTable.tsx, ui/src/components/ValidatorDetails/Details.tsx, ui/src/components/ValidatorDetails/EditEntryGating.tsx, ui/src/components/ValidatorDetails/EditValidatorModal.tsx, ui/src/components/ValidatorInfoRow.tsx, ui/src/components/ValidatorTable.tsx, ui/src/interfaces/validator.ts, ui/src/utils/contracts.ts, ui/src/utils/validation.ts
Previously, the `AddValidatorForm` fieldset for entry gating had a simple UI for gating by asset ID. The user would enter 1-4 asset IDs and as long as they were positive integers they would pass validation and be sent to the registry contract on submission.
This updates the asset ID fields to use the `AssetLookup` component created for setting a reward token. It performs a debounced lookup of the input value and displays the asset's unit name if found (failing validation if not).
We've also decided on some additional constraints for `gatingAssetMinBalance`: it can only be set if there is a single gating asset. The form expects a whole unit amount that will be converted to base units on submission. Only one asset's `decimals` param can be used for the conversion.
If there are multiple …
=> feat(ui): AddValidatorForm entry gating updates

ui/src/components/DebouncedInput.tsx, ui/src/components/DebouncedSearch.tsx, ui/src/components/StakingTable.tsx, ui/src/components/ValidatorTable.tsx, ui/src/interfaces/table.d.ts, ui/src/utils/table.ts
Previously the validator filter only searched owner addresses or NFD names. Now it also searches reward token and gating assets by their ID, name, and unit name.
This also adds a filter to show/hide sunsetted validators, which defaults to hide.
Both of these filters are persisted in local storage, so between page refreshes and route navigations they will remain when you revisit the dashboard.
=> feat(ui): ValidatorTable global search and sunset filter

ui/src/components/Footer.tsx, ui/src/components/Layout.tsx, ui/src/components/Loading.tsx, ui/src/components/PageHeader.tsx, ui/src/components/PageMain.tsx, ui/src/routes/index.tsx, ui/tsconfig.json, ui/tsconfig.node.json, ui/vite-env.d.ts, ui/vite.config.ts
This adds a footer that dynamically displays the current version by importing `version` from the UI's `package.json` file. This value is set to a global constant `__APP_VERSION__` defined in the Vite config. See https://vitejs.dev/config/shared-options.html#define
The footer includes links to GitHub and the GitBook documentation.
The parent layout is also updated to be a flexbox column with the `<main>` element `flex-grow: 1;` to fill the available space. This forces the new footer to the bottom of the viewport even if the page content doesn't reach that far.
=> feat(ui): add footer with current protocol/app version

.github/pull_request_template.md
- Added in a default PR template to repo
- I copied version from `use-wallet` repo (wasn't sure if was your organization template, but it works)
=> ci: add in default PR template

pnpm-lock.yaml, ui/package.json
This also installs @testing-library/dom, which as of RTL v16 is a peer dependency.
=> chore(ui): upgrade @testing-library/react to v16.0.0

pnpm-lock.yaml, ui/package.json
This updates use-wallet to the latest release candidate, which includes a fix for mismatched `algosdk` versions.
Now the library expects `algosdk` to be installed by the consuming application as a peer dependency, to prevent an error that occurs if the library uses a different version than the app.
=> chore(ui): upgrade @txnlab/use-wallet-react to v3.0.0-rc.3

ui/tsconfig.json, ui/tsconfig.node.json, ui/vite.config.mjs
When TypeScript is upgraded to the latest version (v5.5.2), UI production builds fail. The error is not particularly helpful to diagnose the issue, but it is related to the transpilation of `vite.config.ts`.
```
$ pnpm run build
> reti-ui@0.9.5 build /Users/drichar/Projects/TxnLab/reti/ui
> tsc && vite build
error TS6305: Output file '/Users/drichar/Projects/TxnLab/reti/ui/vite.config.d.ts' has not been built from source file '/Users/drichar/Projects/TxnLab/reti/ui/vite.config.ts'.
The file is in the program because:
Matched by include pattern 'vite.config.ts' in '/Users/drichar/Projects/TxnLab/reti/ui/tsconfig.json'
tsconfig.json:30:46
30   "include": ["src/**/*.ts", "src/**/*.tsx", "vite.config.ts", "vitest.setup.ts", "vite-env.d.ts"],
~~~~~~~~~~~~~~~~
File is matched by include pattern …
```
=> chore(ui): rename vite.config.ts -> vite.config.mjs

.prettierrc, renovate.json
This updates the Renovate schedule to only create new pull requests for `ui` dependencies once a month, instead of every week.
Since there was no Prettier configuration at the repository root, automatic formatting on save falls back to the defaults of whatever IDE you're using. It was changing the indentation to tabs in `renovate.json`. This adds a basic Prettier config to the project root to prevent that.
Each project's Prettier config (`contracts`, `bootstrap`, and `ui`) will override this configuration. It only applies to files in the repo root.
=> chore: update Renovate schedule

ui/src/api/algod.ts, ui/src/api/clients.ts, ui/src/api/contracts.ts, ui/src/utils/balanceChecker.ts, ui/src/utils/development.tsx, ui/src/utils/paramsCache.spec.ts, ui/src/utils/paramsCache.ts
Upgrading to the latest version of `@algorandfoundation/algokit-utils` introduces deprecation notices for methods that were previously exposed using a namespace import of the package:
```ts
import * as algokit from '@algorandfoundation/algokit-utils'
// example
const algodClient = algokit.getAlgodClient({ ... })
```
These clients are now created using a `ClientManager`. Using the above example:
```ts
import { ClientManager } from '@algorandfoundation/algokit-utils/types/client-manager'
const algodClient = ClientManager.getAlgodClient({ ... })
```
The `getAlgodClient` and `getKmdClient` methods have been updated according to the notices' instructions.
Also, the `getTestAccount` method in https://github.com/TxnLab/reti/blob/ea9d362d1e0ea0c864da816d69476283304b52e6/ui/src/utils/development.ts …
=> chore(ui): update deprecated algokit methods

.github/workflows/ci-tests.yaml, contracts/__test__/contracts.test.ts, contracts/helpers/helpers.ts, contracts/jest.config.js, contracts/package.json, pnpm-lock.yaml, renovate.json
- Migrates contracts testing framework to Vitest
- Adds `await` to `sendRawTransaction` in `incrementRoundNumberBy` helper function
- Updates Renovate config to no longer separately group Jest dependencies
- Adds contracts test run to CI workflow on pull requests into `main` branch
=> test(contracts): migrate from Jest to Vitest

ui/vite.config.mjs
This PR enhances the `replaceVersionPlugin` in the Vite configuration by using the configured output directory when writing the `version.json` file. The plugin now captures the `outDir` from the Vite config and uses this value when determining the path for the new `version.json` file.
This change allows the build process to work correctly when a custom output directory is specified, resolving an issue where the plugin would fail to find the `version.json` file in the expected location.
- Add `configResolved` hook to capture `outDir` from Vite config
- Replace hardcoded 'dist' with `outDir` when writing `version.json`
- Ensure `version.json` is created in the correct output directory during build
=> fix(ui): use configured outDir for replace version plugin

ui/src/routeTree.gen.ts, ui/src/routes/validators_.$validatorId.tsx
This PR updates the route IDs in the auto-generated router files to match Tanstack Router v1.63.2's updated syntax for non-nested routes. These changes were automatically generated when running the UI's `dev` script after upgrading from v1.56.5.
- Add explicit route `id` fields to match new Tanstack Router requirements
- Update validator detail route ID from `/validators/$validatorId` to `/validators_/$validatorId` to follow non-nested route syntax
- Maintain existing route paths and functionality
=> fix(ui): update route IDs for non-nested validator routes

.vscode/settings.json
Removes the automatic import organization on save from VS Code workspace settings to preserve existing import orders and prevent unnecessary changes.
- Remove `source.organizeImports` from `editor.codeActionsOnSave`
- Maintain existing ESLint and Prettier formatting settings
- Prevents unwanted import reordering that pollutes git diffs with non-functional changes
=> fix(vscode): remove auto-organize imports setting

README.md, ui/src/components/Footer.tsx, ui/src/vite-env.d.ts
This PR adds an optional footer item with URL based on the build time env vars. 
Two new env vars :
* VITE_FOOTER_EXTRA_ITEM - item label
* VITE_FOOTER_EXTRA_ITEM_HREF - item URL 
When VITE_FOOTER_EXTRA_ITEM env var is defined at build time, an extra item is added to the dashboard footer.
Example:
```bash
VITE_FOOTER_EXTRA_ITEM="Nodely DISCLAIMER"
VITE_FOOTER_EXTRA_ITEM_HREF=https://nodely.io/docs/public/reti/
```
=> feat(ui): optional extra footer item

ui/src/api/clients.ts
This PR increases the default transaction validity window to address user-reported issues with transaction signing timeouts, particularly when using hardware wallets like Ledger.
- Modified `algorandClient` configuration to set default validity window to 200 rounds
=> fix(ui): increase default transaction validity window

ui/src/hooks/useCheckForUpdates.ts, ui/vite.config.mjs
This PR enhances the version check system to prevent incorrect update notifications and adds better caching prevention. Previously, users could sometimes see update notifications for older versions due to (suspected) caching issues and imprecise version comparison.
- Add `isNewerVersion` helper to properly compare semver versions
- Add cache-busting query parameter and headers to version check request
- Only show update notification when deployed version is newer than current version
- Add detailed logging to help diagnose version comparison issues
- Improve error handling for failed version checks
=> fix(ui): prevent incorrect update notifications

ui/src/hooks/useCheckForUpdates.ts
This PR enhances the version check system with more robust cache prevention headers. While [`v0.12.1` (release)](https://github.com/algorandfoundation/reti/releases/tag/v0.12.1) added initial cache-busting via query parameters, this change implements a more standards-compliant approach using HTTP cache validation headers.
- Change fetch cache mode to `no-cache` to work better with HTTP caching model
- Add `If-None-Match` and `If-Modified-Since` validation headers
- Maintain existing cache-busting query parameter as additional safeguard
- Allow proper 304 Not Modified responses for better efficiency
=> fix(ui): strengthen version check cache prevention

ui/src/components/ValidatorDetails/StakingDetails.tsx, ui/src/components/ValidatorTable.tsx
This PR temporarily removes APY display functionality from validator-related components due to inconsistent calculations causing misleading information for stakers.
- Remove APY column from `ValidatorTable` component
- Remove APY display sections from `StakingDetails` component
- Clean up unused APY-related imports and query logic
- Hide APY information until calculation issues can be resolved to prevent misleading staking decisions
=> refactor(ui): remove APY display from validator components

ui/src/components/ui/sonner.tsx
fixes a z index issue where the toast would prevent users on mobile using pera from being able to click the open pera button from the popup
=> fix(ui): resolve toast issue with pera mobile

ui/src/hooks/useStakersChartData.ts, ui/src/utils/tests/msw/handlers.ts
This PR enhances the staker list in validator details by integrating NFD name resolution. When a staker has an associated NFD name, it will be displayed instead of their Algorand address and link to their NFD profile instead of the explorer.
- Added NFD lookups for all staker addresses using `useQueries`
- Updated display to show NFD names when available, falling back to addresses
- Modified links to point to NFD profiles when NFD names exist
- Maintained existing explorer links for addresses without NFDs
- Added MSW handlers to mock NFD lookup requests in tests
- Returns mock NFD data for test account
- Returns 404 for addresses without NFDs
- Handles CORS preflight requests
=> feat(ui): display NFD names for stakers in validator details

ui/src/components/ValidatorDetails/StakingDetails.tsx
This PR updates the `StakingDetails` component to show Pool 1 by default when a validator has pools, rather than showing the "All Pools" view. The "All Pools" view is only shown by default when a validator has no pools.
- Changed initial `selectedPool` state to default to Pool 1 when pools exist
- Maintained "All Pools" default for validators with no pools to show empty state
=> fix(ui): default to pool 1 view when pools exist

ui/src/api/contracts.ts
This PR fixes a transaction reference limit error that occurs when attempting to stake to asset-gated validator pools by adding a second gas transaction to handle the additional references needed.
- Add second dummy "gas" transaction to provide sufficient transaction references
- Fix "No more transactions below reference limit" error when staking to asset-gated pools
=> fix(ui): add second gas txn for asset-gated stake

ui/src/hooks/useValidator.ts
This PR fixes a bug in the `useValidator` hook where gating assets were being incorrectly assigned to the `rewardToken` property when no reward token existed. This was caused by array destructuring confusion between reward token and gating asset queries.
- Separate reward token and gating asset queries into distinct calls
- Replace `useSuspenseQueries` with conditional `useQuery` for reward token fetching
- Maintain existing validation logic for both query types
- Ensure gating assets are correctly assigned to their proper property
=> fix(ui): fix incorrect reward token assignment in useValidator

ui/src/api/contracts.ts
This PR fixes an issue in the `addValidator` contract call where floating point precision was causing errors when setting the `percentToValidator` parameter. Valid input values like '4.69' were resulting in floating point imprecision (46900.00000000001) when multiplied by 10000.
- Added `Math.round()` to ensure clean integer conversion when multiplying `percentToValidator` by 10000
- Maintains existing validation that allows up to 4 decimal places
- Ensures valid inputs like '4.69' are handled correctly in the contract call
=> fix(ui): ensure percentToValidator is rounded to integer

ui/src/api/contracts.ts, ui/src/utils/validation.ts
This PR fixes validation handling for decimal inputs in validator forms, including support for values starting with a point (e.g. `.169`) and proper conversion of decimal values to microAlgos.
- Update regex pattern in `minEntryStake` validation to accept leading decimal points
- Update regex pattern in `rewardTokenRefinement` validation to handle leading decimal points
- Fix `minEntryStake` conversion to use `Number` instead of `BigInt` to support decimal values
=> fix(ui): handle decimal inputs in validator forms

ui/src/components/ValidatorDetails/LinkPoolToNfdModal.tsx
This PR fixes an issue with NFD query keys in `LinkPoolToNfdModal` following the `algosdk` v3 migration: https://github.com/algorandfoundation/reti/pull/330
The fix ensures proper address handling for NFD lookups.
- Convert `algosdk.Address` object to string when using as query key
- Fix compatibility with `algosdk` v3's new `getApplicationAddress` return type
- Maintain correct NFD lookup functionality for pool linking
=> fix(ui): convert pool address to string for NFD query key

ui/src/components/ui/sonner.tsx
This PR fixes an issue with toast notification layering that emerged from PR #344. While the previous fix prevented toasts from blocking the Pera Connect modal's launch button, it caused toasts to display behind our application's modal overlays.
- Optimize `Toaster` component's `z-index` to work with multiple overlay scenarios:
- Set `z-index` to `99999` to display above app modals (`z-index: 50`)
- Position below Pera Connect modal (`z-index: 999999`)
- Fix regression where toasts were hidden behind overlay screens
- Maintains fix from #344 while ensuring toasts remain visible above app modals
=> fix(ui): adjust toast z-index to resolve overlay conflicts

ui/src/hooks/useValidators.ts
This PR fixes an issue where validator data could become mismatched when navigating from a validator details page back to the dashboard. The mismatch occurred because some validator data was already cached, causing the array positions in the queued query results to not align with validator IDs.
- Previously relied on array positions to match validator data with IDs
- When some data was cached (e.g., after viewing validator details), the array positions would not match the expected validator IDs
- Now using `queryClient.getQueryData()` with exact query keys to fetch data for each validator
- This ensures correct data matching regardless of cache state
- Removed dependency on array positions in query results
- Maintains correct validator ID relationships when combining data from multiple …
=> fix(ui): maintain validator ID relationships in combined queries

ui/src/api/contracts.ts, ui/src/hooks/useValidator.ts
This PR addresses two issues in the validator details page: missing NFD user-defined properties and missing Algod version display. It enhances type safety for pool data mapping and ensures complete NFD data fetching.
- Add `view: 'full'` parameter to NFD query to include user-defined `bio` property
- Improve type safety in `fetchValidatorPools` using `satisfies` operator
- Fix property name from `poolAlgodVersion` to `algodVersion` to correctly display Algod version
- Ensure compile-time checking for `LocalPoolInfo` property mappings
Both issues were caught during pre-release testing and have been fixed before deployment to production.
=> fix(ui): fetch full NFD view and improve pool type safety

ui/src/api/contracts.ts
This PR fixes an issue where users with stakes in pools containing many stakers (100+) were unable to view their stakes in the "My Stakes" dashboard section due to insufficient transaction fees.
- Increased `extraFee` for `getStakerInfo` call from 3000 to 20000 microAlgos
- Removed redundant `callGetStakerInfo` helper function
- Inlined the contract call with updated fee
- Ensures proper fee coverage for iterating through large staker lists
=> fix(ui): increase extraFee for getStakerInfo call

ui/src/api/contracts.ts, ui/src/components/AddValidatorForm.tsx, ui/src/components/ValidatorDetails/Details.tsx, ui/src/components/ValidatorDetails/ValidatorDetails.tsx, ui/src/interfaces/validator.ts, ui/src/utils/contracts.ts, ui/src/utils/validation.ts
This PR adds support for configuring the maximum stake per pool when creating a validator. The feature allows users to set a limit on how much ALGO can be staked in each pool, with the option to use the protocol maximum as a default.
- Added `maxAlgoPerPool` field to the validator creation form
- Implemented validation to ensure input is a whole number in millions of ALGO
- Updated the `addValidator` function to convert user input to microAlgos
- Added descriptions and tooltips to guide users on proper input format
- Added display of max stake per pool in the validator details page
- Ensured the field is only displayed when a value greater than zero is set
=> feat(ui): add max stake per pool to validator configuration

ui/src/utils/contracts.ts
This PR fixes a critical bug in the max stake per pool calculation where the protocol's maximum per pool constraint (70M ALGO) was not being properly applied when no custom limit was configured. This resulted in displaying values that exceeded the protocol maximum.
- Fix calculation to correctly apply protocol constraints in all scenarios
- Refactor implementation to calculate the applicable maximum (custom or protocol) once upfront
- Simplify logic with early return when there are no pools
- Use `BigMath.min` to properly compare all relevant limits
- Rename variables for clarity and consistency
- Ensure displayed maximum stake per pool is always accurate and never exceeds protocol-defined limits
=> fix(ui): correct max stake per pool calculation logic

ui/src/components/AddStakeModal.tsx
This PR fixes an issue where users experienced transaction failures when using the "Max" button in the Add Stake modal. The fix adds a buffer to the maximum stake calculation to ensure sufficient funds remain for transaction fees.
- Added a 0.26 ALGO buffer to the `stakerMaximumStake` calculation (totaling 0.5 ALGO when combined with the existing fee estimation)
- This ensures users always have enough funds to cover transaction fees, even in complex transaction groups
- The buffer is a negligible amount compared to stake amounts but prevents frustrating transaction failures
- Users reported that reducing the amount slightly allowed transactions to succeed, confirming that a small buffer is all that's needed
=> fix(ui): add buffer to max stake calculation

contracts/bootstrap/package.json, contracts/package.json, ui/package.json, ui/src/components/ValidatorTable.tsx, ui/src/utils/contracts.spec.ts, ui/src/utils/contracts.ts
- Added `isFirstPoolFull` utility function to check if the first pool of a validator is full
- Updated `isStakingDisabled` to account for the first pool being full
- Modified `ValidatorTable` to disable staking button and show 'Full' if the first pool is full
- Included tests for the new `isFirstPoolFull` logic
=> fix(ui): disable staking when first pool is full because of v1 findPoolForStaker bug

ui/src/api/contracts.ts, ui/src/components/ValidatorRewards.tsx, ui/src/components/ValidatorTable.tsx, ui/src/utils/contracts.ts, ui/src/utils/table.ts
feat(ui): refactor pool data processing and add validator rewards display
--
Refactor `processPoolData` to fetch data in parallel, improving efficiency and clarity.
Introduce `ValidatorRewards` component to display pending rewards in the `ValidatorTable`.
- Replaced sequential async calls in `processPoolData` with `Promise.all`
- Added `ValidatorRewards` component for reward display
- Updated `ValidatorTable` to include a "Pend. Rewards" column
- Simplified rewards balance calculation logic
feat(ui): add ineligible stake filter
--
Introduce a column filter for ineligible validators based on `MIN_ELIGIBLE_STAKE`. 
Added a new `ineligibleFilter` function to determine eligibility by staking amount and updated `ValidatorTable` to allow toggling visibility of ineligible validators.
Display the …
=> UI touchup

.github/workflows/ci-ui.yaml, renovate.json, ui/package.json
This PR ensures consistent pnpm version usage across all deployment and development environments by pinning to `pnpm@9.15.9`.
- Added `packageManager` field to UI `package.json` specifying `pnpm@9.15.9` for Corepack compatibility
- Updated CI workflow to use `pnpm@9.15.9` instead of `9.2.0` for version consistency
- Configured Renovate to ignore `packageManager` field updates to prevent automatic pnpm version bumps
- Ensures Vercel deployments use the intended pnpm version via Corepack integration
=> chore(ui): pin pnpm version to 9.15.9 across environments
